#!/usr/bin/python3
#initialize system
from kerbmath.system import System
sys = System()
sys.readconf("kerbol.cfg")

#launch session
from kerbmath.util import interact
interact(sys.__dict__, "Kerbmath Interactive Shell (c) 2013 by Michael Ensslin <michael@ensslin.cc>")
